[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2021"

[dependencies]
bracket-lib = "~0.8.1"
legion = "=0.3.1"
ron = "=0.6.1"
serde = { version = "=1.0.115" }

[profile.release]
lto = "thin"
